name: docker-kernel-panic-test
version: '0.0.1'
summary: A snap to reproduce a kernel panic issue
description: |
  A test snap used to reproduce a kernel panic issue when run docker command in a snap

grade: devel
confinement: devmode

apps:
  dockertest:
    command: dockertest
    plugs:
      - docker

parts:
  dockertest:
    plugin: python
    python-version: python2
    source: src
